services:
  nuclio:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.13.0-amd64
    restart: always
    depends_on:
      nuclio-local-storage-reader:
        condition: service_started
    networks:
      cvat:
        ipv4_address: 172.20.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy=${no_proxy:-}
      - NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS=true
      - NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE=volume
      - NUCLIO_LOCAL_STORAGE_READER_NETWORK=cvat
      - NUCLIO_LOCAL_STORAGE_READER_IP=172.20.0.22
    ports:
      - "8070:8070"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  nuclio-local-storage-reader:
    container_name: nuclio-local-storage-reader
    image: gcr.io/iguazio/alpine:3.17
    restart: always
    command: tail -f /dev/null
    networks:
      cvat:
        ipv4_address: 172.20.0.22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cvat_server:
    environment:
      - CVAT_SERVERLESS=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      cvat:
        ipv4_address: 172.20.0.30

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      cvat:
        ipv4_address: 172.20.0.16

networks:
  cvat:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
