---
apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: sam2-tce
  namespace: cvat
  annotations:
    name: Segment Anything 2
    version: 2
    type: interactor
    min_pos_points: "1"
    min_neg_points: "0"
    startswith_box_optional: "true"
    animated_gif: https://raw.githubusercontent.com/cvat-ai/cvat/develop/site/content/en/images/hrnet_example.gif
    help_message: The interactor allows to get a mask of an object using at least one positive point

spec:
  description: Interactive object segmentation with Segment-Anything
  runtime: python:3.8
  handler: main:handler
  eventTimeout: 30s

  build:
    image: cvat.sam2.tce:7e1596c
    baseImage: pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel
    directives:
      preCopy:
        - kind: ENV
          value: NVIDIA_VISIBLE_DEVICES=all
        - kind: ENV
          value: NVIDIA_DRIVER_CAPABILITIES=compute,utility
        - kind: ENV
          value: DEBIAN_FRONTEND=noninteractive
        - kind: ENV
          value: TORCH_CUDA_ARCH_LIST="9.0 8.0 8.6 8.9 7.0 7.2 7.5 6.0"
        - kind: ENV
          value: MODEL="sam2_hiera_tiny.pt"
        - kind: ENV
          value: MODEL_CFG="sam2_hiera_t.yaml"
        - kind: ENV
          value: PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
        - kind: WORKDIR
          value: /opt/nuclio/sam2
        - kind: RUN
          value: >
            apt-get update && apt-get -y install curl git ffmpeg libsm6
            libxext6 build-essential
        - kind: RUN
          value: >
            pip install --no-cache-dir
            git+https://github.com/facebookresearch/segment-anything-2.git@main
            opencv-python
        - kind: RUN
          value: >
            curl -O
            https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt
        - kind: RUN
          value: >
            curl -O
            https://raw.githubusercontent.com/facebookresearch/segment-anything-2/main/sam2/configs/sam2_hiera_t.yaml

  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: http
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: "25m"
      memory: "1Mi"

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
      network: cvat_cvat
